version: '3.8'

services:

  # Loki для сбора логов
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
      - ./config/loki:/etc/loki
    networks:
      - monitor-overlay
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1

  # Promtail для отправки логов в Loki
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail:/etc/promtail
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-overlay
    deploy:
      mode: global

  # Grafana для визуализации
  grafana:
    image: grafana/grafana:9.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    networks:
      - monitor-overlay
    depends_on:
      - loki
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1

volumes:
  loki_data:
    driver: local
  grafana_data:
    driver: local

networks:
  monitor-overlay:
    driver: overlay
    attachable: true