volumes:
  redis_data:
    driver: local
  mysql_lib_data:
    driver: local
  postgres_data:
    driver: local
  www_data:
    driver: local
  bxtemp_data:
    driver: local
  msmtp_data:
    driver: local
  browscap_data:
    driver: local
  geoip2_data:
    driver: local
  ssl_data:
    driver: local
services:
  memcached:
    image: memcached:1.6.39-alpine
    deploy:
      placement:
        constraints:
          - node.role != manager
    container_name: dev_memcached
    restart: unless-stopped
    env_file:
      - .env
#    ports:
#      - "11211:11211"
    init: true
    #cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - memcached
  redis:
    image: redis:7.2.10-alpine
      #  deploy:
      #placement:
      #  constraints:
      #    - node.role != manager
    container_name: dev_redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - .env
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./confs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    init: true
#    cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - redis
  postgres:
    image: postgres:16.10-bookworm
    deploy:
      placement:
        constraints:
          - node.role != manager
    container_name: dev_postgres
    restart: unless-stopped
    env_file:
      - .env
      - .env_sql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    init: true
#   cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETUID
      - SETGID
      - DAC_OVERRIDE
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - postgres
  php:
    image: quay.io/bitrix24/php:8.2.29-fpm-v1-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager
    container_name: dev_php
    restart: unless-stopped
    env_file:
      - .env
      - .env_php
#    ports:
#      - "9000:9000"
    volumes:
      - ./confs/php82/etc/:/usr/local/etc/
      #- ./confs/php83/etc/:/usr/local/etc/
      #- ./confs/php84/etc/:/usr/local/etc/
      - www_data:/opt/www/
      - bxtemp_data:/opt/.bx_temp/
      - msmtp_data:/opt/msmtp/
      - browscap_data:/opt/browscap/
      - geoip2_data:/opt/geoip2/
      - ssl_data:/ssl/
    init: true
#    cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - php
    depends_on:
      - postgres
  nginx:
    image: quay.io/bitrix24/nginx:1.28.0-v1-alpine
    container_name: dev_nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8588:80"
      - "8589:443"
    volumes:
      - ./confs/nginx/:/etc/nginx/
      - www_data:/opt/www/
      - bxtemp_data:/opt/.bx_temp/
      - ssl_data:/ssl/
    init: true
#   cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - nginx
  push-sub:
    image: quay.io/bitrix24/push:3.1-v1-alpine
    deploy: 
      placement: 
        constraints: 
          - node.role != manager
    container_name: dev_push_sub
    restart: unless-stopped
    env_file:
      - .env
      - .env_push
      - .env_push_sub
      - .env_redis
#    ports:
#      - "8010:8010"
    init: true
#    cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - push_sub
    depends_on:
      - redis
  push-pub:
    image: quay.io/bitrix24/push:3.1-v1-alpine
    deploy: 
      placement: 
        constraints: 
          - node.role != manager
    container_name: dev_push_pub
    restart: unless-stopped
    env_file:
      - .env
      - .env_push
      - .env_push_pub
      - .env_redis
#    ports:
#      - "9010:9010"
    init: true
#    cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - push_pub
    depends_on:
      - redis
  sphinx:
    image: quay.io/bitrix24/sphinx:2.2.11-v1-alpine
    deploy: 
      placement: 
        constraints: 
          - node.role != manager
    container_name: dev_sphinx
#    ports:
#      - "9306:9306"
#      - "9312:9312"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./confs/sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf
    init: true
#   cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - sphinx
  cron:
    image: quay.io/bitrix24/php:8.2.29-fpm-v1-alpine
      #    deploy: 
      # placement: 
      #  constraints: 
      #    - node.role != manager
    container_name: dev_cron
    restart: unless-stopped
    command: crond -f -d 8
    user: root
    env_file:
      - .env
      - .env_php
#    ports:
#      - "9001:9000"
    volumes:
      - ./confs/php82/etc/:/usr/local/etc/
      - www_data:/opt/www/
      - bxtemp_data:/opt/.bx_temp/
      - msmtp_data:/opt/msmtp/
      - browscap_data:/opt/browscap/
      - geoip2_data:/opt/geoip2/
    init: true
#   cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - cron
    depends_on:
      - php
  ssl:
    image: quay.io/bitrix24/ssl:1.0-v1-alpine
    deploy: 
      placement: 
        constraints: 
          - node.role != manager
    container_name: dev_ssl
    restart: unless-stopped
    env_file:
      - .env
      - .env_ssl
    volumes:
      - ssl_data:/ssl/
    init: true
#    cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - ssl
    depends_on:
      - nginx
  lego:
    image: quay.io/bitrix24/lego:4.25.2-v1-alpine
    deploy: 
      placement: 
        constraints: 
          - node.role != manager
    container_name: dev_lego
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ssl_data:/ssl/
    init: true
#   cgroup: host
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:noexec,nodev,nosuid
      - /var/tmp:noexec,nodev,nosuid
      - /dev/shm:noexec,nodev,nosuid
    networks:
      dev:
        aliases:
          - lego
    depends_on:
      - nginx
networks:
  dev:
    driver: overlay
    attachable: true
    internal: false
